apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "webapidotnet.fullname" . }}
data:
{{- range $key, $value := .Values.configmapEnv }}
  {{ printf "%v" $key }}: {{ $value | quote }}
{{- end }}