apiVersion: v1
kind: Secret
metadata:
  name: {{ template "webapidotnet.fullname" . }}
type: Opaque
stringData:
  user: {{ .Values.secrets.MongoDB__User }}
  password: {{ .Values.secrets.MongoDB__Password }}