trigger:
- none

pool:
  name: linux-agent-pool

variables:
- group: anandvariablegroup

steps:
  - task: PackerBuild@1
    displayName: 'Build a Packer Image'
    inputs:
      templateType: 'custom'
      customTemplateLocation: 'vm.json'
      customTemplateParameters: '{"clientsecret":"$(clientsecret)"}'

