apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  suspend: {{ .Values.suspend }}
  successfulJobsHistoryLimit : {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "cronjob.selectorLabels" . | nindent 8 }}
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
        {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            args:
            {{- toYaml .Values.args | nindent 14 }}
          restartPolicy: {{ .Values.restartPolicy }}


